### PR TITLE
Created Tests and added docstrings with helper text.

### PR DESCRIPTION
**Pull request by rsauosci**
Tests for library and docstrings.

### CODE REVIEW

**Comment by rsauosci** [comment]
dont approve yet i'm working on getting automation to work.

**Comment by rsauosci** [comment]
Automation is working now.

**Review by aesse97 — APPROVED** [review]
This all looks good code-wise, if works with our scripts then this is awesome and good to have

**Comment by rsauosci** [comment]
> This all looks good code-wise, if works with our scripts then this is awesome and good to have

Some minor changes need to be made to references otherwise all logic should work the same.

**Pull request merged**
